### PR TITLE
add dns cache

### PR DESCRIPTION
**Pull request by adriadam10**

### CODE REVIEW

**Comment by dmunozv04** [comment]
Quick question, would it be better to reuse the aiohttp session on all requests instead of making a new one each time?

**Comment by FabioGNR** [comment]
Thanks for submitting the PR!
Running the test.py file to try it out, I got a "Session closed" error on the second request I believe.
I guess the session closes the connector which leads to failure the next time.
Either way I agree with @dmunozv04, I think it's better to reuse the session itself.

I'm currently experimenting with this on branch "reuse-session".
However locally I cannot see any DNS request being made after the initial one, so I cannot test the TTL.
It seems there's some other cache still active.

If you have the time please help me out with testing this branch :)

**Comment by FabioGNR** [comment]
Thanks, it does successfully connect now but I get these issues on exit:
```
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff046719d30>, 353.84373817)]']
connector: <aiohttp.connector.TCPConnector object at 0x7ff046d5e3d0>
```

This is because the session is not closed properly.
I've already handled this issue on the "reuse-session" branch. Are you able to test if that branch works for your use case?

**Comment by dmunozv04** [comment]
@adriadam10 you could clone my project and set as a dependency this repository using git. I suspect that aiohttp will complain about the unclosed session there too. 
I think the solution would be to detect if you pass an already made aiohttp session or if you create one, and only close it if it was created for this purpose when the object is destroyed with the `__exit__` dunder or some other

**Comment by FabioGNR** [comment]
In the 2.0.0 release this functionality was merged along with some tweaks and additions.
Thank you for your contribution!

**Comment by dmunozv04** [comment]
@FabioGNR Thanks for adding this functionality!

**Pull request closed without merging**
